/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_b0d68fc8 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/azimhqpsjgxbmjlxaghp/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

function getRequiredEnv(name: string): string {
  const value = Deno.env.get(name);
  if (!value) {
    throw new Error(`Missing environment variable: ${name}`);
  }
  return value;
}

const client = () => createClient(
  getRequiredEnv("SUPABASE_URL"),
  getRequiredEnv("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_b0d68fc8").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async <T = unknown>(key: string): Promise<T | null> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_b0d68fc8").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return (data?.value as T | undefined) ?? null;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_b0d68fc8").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_b0d68fc8").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async <T = unknown>(keys: string[]): Promise<T[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_b0d68fc8").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return (data?.map((d) => d.value as T) ?? []);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_b0d68fc8").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async <T = unknown>(prefix: string): Promise<T[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_b0d68fc8").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return (data?.map((d) => d.value as T) ?? []);
};
