/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const env = (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env ?? {};

const DEFAULT_PROJECT_ID = "vcixsdudkizgfikhmfuv";
const DEFAULT_LEGACY_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaXhzZHVka2l6Z2Zpa2htZnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5OTIyMjgsImV4cCI6MjA4NzU2ODIyOH0.Gk3PIFWYzEWwqTJ11E81WVQGtNyFZOdHa7PitY_Sf5o";

export const projectId = env.VITE_SUPABASE_PROJECT_ID || DEFAULT_PROJECT_ID;
export const publicAnonKey =
  env.VITE_SUPABASE_ANON_KEY ||
  env.VITE_SUPABASE_LEGACY_ANON_KEY ||
  DEFAULT_LEGACY_ANON_KEY;

// Optional exports for new callers migrating to env-based config.
export const supabaseUrl = env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;
export const publishableKey = env.VITE_SUPABASE_PUBLISHABLE_KEY || "";
