/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

import { runtimeFlags } from '/utils/runtimeConfig';
import { resolveSupabasePublicConfig } from './publicConfig';

const env = (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env ?? {};

const DEFAULT_PROJECT_ID = "ystjugghyteyylkevbsl";
const DEFAULT_LEGACY_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdGp1Z2doeXRleXlsa2V2YnNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1Njg2MTgsImV4cCI6MjA5NjE0NDYxOH0.hdosVyDFd12pk80bGnJFkBOqVqhxwaz9l5bNKwJNo-I";

const resolved = resolveSupabasePublicConfig(
  env,
  {
    projectId: DEFAULT_PROJECT_ID,
    publicKey: DEFAULT_LEGACY_ANON_KEY,
  },
  runtimeFlags.enableSupabaseConfigFallback,
);

if (resolved.warning && typeof console !== 'undefined') {
  console.warn(`[SupabaseConfig] ${resolved.warning}`);
}

export const projectId = resolved.projectId;
export const publicAnonKey = resolved.publicKey;
export const supabaseUrl = resolved.supabaseUrl;
export const publishableKey = resolved.publishableKey;
