import type { GeoCountry, GeoPlace } from '@/types/address';

export const GEO_SEED_COUNTRIES: GeoCountry[] = [
  {
    code: 'US',
    iso3: 'USA',
    name: 'United States',
    phoneCode: '+1',
    postalCodeLabel: 'ZIP code',
    postalCodeRequired: true,
    postalCodePattern: '^[0-9]{5}(-[0-9]{4})?$',
    addressSchema: {
      levels: [
        { kind: 'admin1', label: 'State', required: true },
        { kind: 'admin2', label: 'County', required: true },
        { kind: 'locality', label: 'City', required: true },
      ],
    },
    isActive: true,
  },
  {
    code: 'CA',
    iso3: 'CAN',
    name: 'Canada',
    phoneCode: '+1',
    postalCodeLabel: 'Postal code',
    postalCodeRequired: true,
    postalCodePattern: '^[A-Za-z]\\d[A-Za-z][ -]?\\d[A-Za-z]\\d$',
    addressSchema: {
      levels: [
        { kind: 'admin1', label: 'Province', required: true },
        { kind: 'locality', label: 'City', required: true },
      ],
    },
    isActive: true,
  },
  {
    code: 'GB',
    iso3: 'GBR',
    name: 'United Kingdom',
    phoneCode: '+44',
    postalCodeLabel: 'Postcode',
    postalCodeRequired: true,
    postalCodePattern: '^[A-Za-z]{1,2}\\d[A-Za-z\\d]? ?\\d[A-Za-z]{2}$',
    addressSchema: {
      levels: [
        { kind: 'admin1', label: 'Nation', required: true },
        { kind: 'locality', label: 'Town / City', required: true },
      ],
    },
    isActive: true,
  },
  {
    code: 'VN',
    iso3: 'VNM',
    name: 'Vietnam',
    nativeName: 'Viet Nam',
    phoneCode: '+84',
    postalCodeLabel: 'Postal code',
    postalCodeRequired: true,
    postalCodePattern: '^[0-9]{5,6}$',
    addressSchema: {
      levels: [
        { kind: 'admin1', label: 'Province / City', required: true },
        { kind: 'admin2', label: 'District', required: true },
        { kind: 'locality', label: 'Ward / Locality', required: true },
      ],
    },
    isActive: true,
  },
  {
    code: 'JP',
    iso3: 'JPN',
    name: 'Japan',
    nativeName: '日本',
    phoneCode: '+81',
    postalCodeLabel: 'Postal code',
    postalCodeRequired: true,
    postalCodePattern: '^\\d{3}-?\\d{4}$',
    addressSchema: {
      levels: [
        { kind: 'admin1', label: 'Prefecture', required: true },
        { kind: 'locality', label: 'City / Ward', required: true },
      ],
    },
    isActive: true,
  },
  {
    code: 'DE',
    iso3: 'DEU',
    name: 'Germany',
    nativeName: 'Deutschland',
    phoneCode: '+49',
    postalCodeLabel: 'Postal code',
    postalCodeRequired: true,
    postalCodePattern: '^\\d{5}$',
    addressSchema: {
      levels: [
        { kind: 'admin1', label: 'State', required: true },
        { kind: 'locality', label: 'City', required: true },
      ],
    },
    isActive: true,
  },
];

export const GEO_SEED_PLACES: GeoPlace[] = [
  {
    id: 'US-CA',
    countryCode: 'US',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'CA',
    name: 'California',
    isSelectable: true,
    sortOrder: 1,
    lat: 36.7783,
    lng: -119.4179,
  },
  {
    id: 'US-CA-SF-COUNTY',
    countryCode: 'US',
    parentId: 'US-CA',
    depth: 2,
    placeKind: 'admin2',
    code: '075',
    name: 'San Francisco County',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'US-CA-SF',
    countryCode: 'US',
    parentId: 'US-CA-SF-COUNTY',
    depth: 3,
    placeKind: 'locality',
    name: 'San Francisco',
    isSelectable: true,
    sortOrder: 1,
    lat: 37.7749,
    lng: -122.4194,
  },
  {
    id: 'US-CA-LA-COUNTY',
    countryCode: 'US',
    parentId: 'US-CA',
    depth: 2,
    placeKind: 'admin2',
    code: '037',
    name: 'Los Angeles County',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'US-CA-LA',
    countryCode: 'US',
    parentId: 'US-CA-LA-COUNTY',
    depth: 3,
    placeKind: 'locality',
    name: 'Los Angeles',
    isSelectable: true,
    sortOrder: 1,
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    id: 'US-NY',
    countryCode: 'US',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'NY',
    name: 'New York',
    isSelectable: true,
    sortOrder: 2,
    lat: 43.2994,
    lng: -74.2179,
  },
  {
    id: 'US-NY-NY-COUNTY',
    countryCode: 'US',
    parentId: 'US-NY',
    depth: 2,
    placeKind: 'admin2',
    code: '061',
    name: 'New York County',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'US-NY-NYC',
    countryCode: 'US',
    parentId: 'US-NY-NY-COUNTY',
    depth: 3,
    placeKind: 'locality',
    name: 'New York',
    isSelectable: true,
    sortOrder: 1,
    lat: 40.7128,
    lng: -74.006,
  },
  {
    id: 'CA-ON',
    countryCode: 'CA',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'ON',
    name: 'Ontario',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'CA-ON-TORONTO',
    countryCode: 'CA',
    parentId: 'CA-ON',
    depth: 2,
    placeKind: 'locality',
    name: 'Toronto',
    isSelectable: true,
    sortOrder: 1,
    lat: 43.6532,
    lng: -79.3832,
  },
  {
    id: 'CA-ON-OTTAWA',
    countryCode: 'CA',
    parentId: 'CA-ON',
    depth: 2,
    placeKind: 'locality',
    name: 'Ottawa',
    isSelectable: true,
    sortOrder: 2,
    lat: 45.4215,
    lng: -75.6972,
  },
  {
    id: 'CA-BC',
    countryCode: 'CA',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'BC',
    name: 'British Columbia',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'CA-BC-VANCOUVER',
    countryCode: 'CA',
    parentId: 'CA-BC',
    depth: 2,
    placeKind: 'locality',
    name: 'Vancouver',
    isSelectable: true,
    sortOrder: 1,
    lat: 49.2827,
    lng: -123.1207,
  },
  {
    id: 'CA-BC-VICTORIA',
    countryCode: 'CA',
    parentId: 'CA-BC',
    depth: 2,
    placeKind: 'locality',
    name: 'Victoria',
    isSelectable: true,
    sortOrder: 2,
    lat: 48.4284,
    lng: -123.3656,
  },
  {
    id: 'GB-ENG',
    countryCode: 'GB',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'ENG',
    name: 'England',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'GB-ENG-LONDON',
    countryCode: 'GB',
    parentId: 'GB-ENG',
    depth: 2,
    placeKind: 'locality',
    name: 'London',
    isSelectable: true,
    sortOrder: 1,
    lat: 51.5072,
    lng: -0.1276,
  },
  {
    id: 'GB-ENG-MANCHESTER',
    countryCode: 'GB',
    parentId: 'GB-ENG',
    depth: 2,
    placeKind: 'locality',
    name: 'Manchester',
    isSelectable: true,
    sortOrder: 2,
    lat: 53.4808,
    lng: -2.2426,
  },
  {
    id: 'GB-SCT',
    countryCode: 'GB',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'SCT',
    name: 'Scotland',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'GB-SCT-EDINBURGH',
    countryCode: 'GB',
    parentId: 'GB-SCT',
    depth: 2,
    placeKind: 'locality',
    name: 'Edinburgh',
    isSelectable: true,
    sortOrder: 1,
    lat: 55.9533,
    lng: -3.1883,
  },
  {
    id: 'GB-SCT-GLASGOW',
    countryCode: 'GB',
    parentId: 'GB-SCT',
    depth: 2,
    placeKind: 'locality',
    name: 'Glasgow',
    isSelectable: true,
    sortOrder: 2,
    lat: 55.8642,
    lng: -4.2518,
  },
  {
    id: 'VN-HCM',
    countryCode: 'VN',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'SG',
    name: 'Ho Chi Minh City',
    isSelectable: true,
    sortOrder: 1,
    lat: 10.8231,
    lng: 106.6297,
  },
  {
    id: 'VN-HCM-Q1',
    countryCode: 'VN',
    parentId: 'VN-HCM',
    depth: 2,
    placeKind: 'admin2',
    code: 'Q1',
    name: 'District 1',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'VN-HCM-Q1-BEN-NGHE',
    countryCode: 'VN',
    parentId: 'VN-HCM-Q1',
    depth: 3,
    placeKind: 'locality',
    name: 'Ben Nghe Ward',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'VN-HCM-Q1-BEN-THANH',
    countryCode: 'VN',
    parentId: 'VN-HCM-Q1',
    depth: 3,
    placeKind: 'locality',
    name: 'Ben Thanh Ward',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'VN-HCM-Q3',
    countryCode: 'VN',
    parentId: 'VN-HCM',
    depth: 2,
    placeKind: 'admin2',
    code: 'Q3',
    name: 'District 3',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'VN-HCM-Q3-VO-THI-SAU',
    countryCode: 'VN',
    parentId: 'VN-HCM-Q3',
    depth: 3,
    placeKind: 'locality',
    name: 'Vo Thi Sau Ward',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'VN-HN',
    countryCode: 'VN',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'HN',
    name: 'Ha Noi',
    isSelectable: true,
    sortOrder: 2,
    lat: 21.0278,
    lng: 105.8342,
  },
  {
    id: 'VN-HN-HOAN-KIEM',
    countryCode: 'VN',
    parentId: 'VN-HN',
    depth: 2,
    placeKind: 'admin2',
    name: 'Hoan Kiem District',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'VN-HN-HOAN-KIEM-TRANG-TIEN',
    countryCode: 'VN',
    parentId: 'VN-HN-HOAN-KIEM',
    depth: 3,
    placeKind: 'locality',
    name: 'Trang Tien Ward',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'VN-HN-BA-DINH',
    countryCode: 'VN',
    parentId: 'VN-HN',
    depth: 2,
    placeKind: 'admin2',
    name: 'Ba Dinh District',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'VN-HN-BA-DINH-KIM-MA',
    countryCode: 'VN',
    parentId: 'VN-HN-BA-DINH',
    depth: 3,
    placeKind: 'locality',
    name: 'Kim Ma Ward',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'JP-13',
    countryCode: 'JP',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: '13',
    name: 'Tokyo',
    isSelectable: true,
    sortOrder: 1,
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    id: 'JP-13-SHIBUYA',
    countryCode: 'JP',
    parentId: 'JP-13',
    depth: 2,
    placeKind: 'locality',
    name: 'Shibuya',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'JP-13-CHIYODA',
    countryCode: 'JP',
    parentId: 'JP-13',
    depth: 2,
    placeKind: 'locality',
    name: 'Chiyoda',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'JP-27',
    countryCode: 'JP',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: '27',
    name: 'Osaka',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'JP-27-OSAKA-CITY',
    countryCode: 'JP',
    parentId: 'JP-27',
    depth: 2,
    placeKind: 'locality',
    name: 'Osaka',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'JP-27-SAKAI',
    countryCode: 'JP',
    parentId: 'JP-27',
    depth: 2,
    placeKind: 'locality',
    name: 'Sakai',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'DE-BE',
    countryCode: 'DE',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'BE',
    name: 'Berlin',
    isSelectable: true,
    sortOrder: 1,
    lat: 52.52,
    lng: 13.405,
  },
  {
    id: 'DE-BE-BERLIN',
    countryCode: 'DE',
    parentId: 'DE-BE',
    depth: 2,
    placeKind: 'locality',
    name: 'Berlin',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'DE-BY',
    countryCode: 'DE',
    parentId: null,
    depth: 1,
    placeKind: 'admin1',
    code: 'BY',
    name: 'Bavaria',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'DE-BY-UPPER-BAVARIA',
    countryCode: 'DE',
    parentId: 'DE-BY',
    depth: 2,
    placeKind: 'admin2',
    name: 'Upper Bavaria',
    isSelectable: true,
    sortOrder: 1,
  },
  {
    id: 'DE-BY-MUNICH',
    countryCode: 'DE',
    parentId: 'DE-BY',
    depth: 2,
    placeKind: 'locality',
    name: 'Munich',
    isSelectable: true,
    sortOrder: 1,
    lat: 48.1351,
    lng: 11.582,
  },
  {
    id: 'DE-BY-MIDDLE-FRANCONIA',
    countryCode: 'DE',
    parentId: 'DE-BY',
    depth: 2,
    placeKind: 'admin2',
    name: 'Middle Franconia',
    isSelectable: true,
    sortOrder: 2,
  },
  {
    id: 'DE-BY-NUREMBERG',
    countryCode: 'DE',
    parentId: 'DE-BY',
    depth: 2,
    placeKind: 'locality',
    name: 'Nuremberg',
    isSelectable: true,
    sortOrder: 1,
    lat: 49.4521,
    lng: 11.0767,
  },
];
